# Generated by Django 5.2.10 on 2026-03-16 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("layers", "0046_remove_modeltranslation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mask_type",
                    models.CharField(default="open_pit_mine", max_length=100),
                ),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                ("total_area_ha", models.FloatField(blank=True, null=True)),
                ("count", models.IntegerField(blank=True, null=True)),
                ("max_area_ha", models.FloatField(blank=True, null=True)),
                ("min_area_ha", models.FloatField(blank=True, null=True)),
                ("avg_ndvi", models.FloatField(blank=True, null=True)),
                ("avg_ndwi", models.FloatField(blank=True, null=True)),
                ("avg_bsi", models.FloatField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_analyses",
                        to="layers.dataset",
                    ),
                ),
            ],
        ),
    ]
