# Generated by Django 5.2.10 on 2026-03-16 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
        ("layers", "0046_remove_modeltranslation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysis",
            options={
                "ordering": ["-analysis_date"],
                "verbose_name": "Inference Run",
                "verbose_name_plural": "Inference Runs",
            },
        ),
        migrations.AddField(
            model_name="analysis",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="input_params",
            field=models.JSONField(
                blank=True,
                help_text="Parameters sent to the AI service (threshold, tile size, etc.)",
                null=True,
                verbose_name="AI Input Parameters",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="result_metadata",
            field=models.JSONField(
                blank=True,
                help_text="Raw JSON result payload from the AI service",
                null=True,
                verbose_name="Full AI Result Metadata",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="shapefile_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the shapefile layer uploaded back to GeoNode",
                null=True,
                verbose_name="Resulting Layer URL",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="job_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="AI Service Job ID",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analyses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="target_dataset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_analyses",
                to="layers.dataset",
                verbose_name="Source Raster Dataset",
            ),
        ),
    ]
