# Generated by Django 5.2.12 on 2026-04-09 02:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OCO2Data",
            fields=[
                (
                    "sounding_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("acquisition_time", models.DateTimeField(db_index=True)),
                ("xco2", models.FloatField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        db_index=True, srid=4326
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["acquisition_time"],
                        name="carbon_trac_acquisi_1b6529_idx",
                    ),
                    models.Index(
                        fields=["location"], name="carbon_trac_locatio_2c33cc_idx"
                    ),
                ],
            },
        ),
    ]
