# Generated by Django 5.2.12 on 2026-04-10 02:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="oco2data",
            name="carbon_trac_acquisi_1b6529_idx",
        ),
        migrations.RemoveIndex(
            model_name="oco2data",
            name="carbon_trac_locatio_2c33cc_idx",
        ),
        migrations.AlterField(
            model_name="oco2data",
            name="acquisition_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="oco2data",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
