# Generated by Django 5.2.12 on 2026-05-01 02:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_tracker", "0003_restore_oco2data_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="VietNamOCO2Data",
            fields=[
                (
                    "sounding_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("acquisition_time", models.DateTimeField(db_index=True)),
                ("xco2", models.FloatField()),
                ("xco2_uncertainty", models.FloatField(blank=True, null=True)),
                ("xco2_quality_flag", models.IntegerField(blank=True, null=True)),
                ("latitude", models.FloatField(db_index=True)),
                ("longitude", models.FloatField(db_index=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("orbit", models.IntegerField(blank=True, null=True)),
                (
                    "operation_mode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("source_file", models.CharField(db_index=True, max_length=500)),
                ("source_folder", models.CharField(db_index=True, max_length=500)),
                ("raw_metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "carbon_tracker_vietnam_oco2data",
                "ordering": ("-acquisition_time", "-sounding_id"),
            },
        ),
    ]
