# Generated by Django 5.2.12 on 2026-05-01 15:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_tracker", "0005_vietnamoco2data_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sounding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sounding_unique_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "observation_request_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "observation_time",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("land_fraction", models.FloatField(blank=True, null=True)),
                ("solar_zenith", models.FloatField(blank=True, null=True)),
                ("solar_azimuth", models.FloatField(blank=True, null=True)),
                ("view_zenith", models.FloatField(blank=True, null=True)),
                ("view_azimuth", models.FloatField(blank=True, null=True)),
                ("solar_distance", models.FloatField(blank=True, null=True)),
                (
                    "specular_view_vector_angle",
                    models.FloatField(blank=True, null=True),
                ),
                ("surface_roughness", models.FloatField(blank=True, null=True)),
                ("sunglint_flag", models.SmallIntegerField(blank=True, null=True)),
                (
                    "detailed_operation_mode",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "scan_direction",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("pointing_at", models.FloatField(blank=True, null=True)),
                ("pointing_ct", models.FloatField(blank=True, null=True)),
                ("ip_request", models.SmallIntegerField(blank=True, null=True)),
                ("yaw_steering_flag", models.SmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "gosat_sounding",
            },
        ),
        migrations.CreateModel(
            name="GosatProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.TextField()),
                ("file_path", models.TextField(blank=True, null=True)),
                ("file_id", models.TextField(blank=True, db_index=True, null=True)),
                (
                    "satellite_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sensor_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "processing_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("algorithm_name", models.TextField(blank=True, null=True)),
                (
                    "algorithm_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "input_data_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "start_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("processing_date", models.DateTimeField(blank=True, null=True)),
                ("processing_facility", models.TextField(blank=True, null=True)),
                (
                    "geodetic_datum",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("num_sounding", models.IntegerField(blank=True, null=True)),
                ("num_layer", models.IntegerField(blank=True, null=True)),
                ("num_band", models.IntegerField(blank=True, null=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "gosat_product",
            },
        ),
        migrations.CreateModel(
            name="H5DatasetCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("h5_path", models.TextField()),
                ("dataset_name", models.TextField(blank=True, null=True)),
                ("h5_group", models.TextField(blank=True, null=True)),
                ("shape", models.TextField(blank=True, null=True)),
                ("dtype", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=100, null=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "gosat_h5_dataset_catalog",
            },
        ),
        migrations.CreateModel(
            name="L1QualityBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("band_index", models.SmallIntegerField()),
                ("snr", models.FloatField(blank=True, null=True)),
                ("snr_synthesized", models.FloatField(blank=True, null=True)),
                (
                    "interferogram_quality_flag",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("missing_flag", models.SmallIntegerField(blank=True, null=True)),
                ("saturation_flag", models.SmallIntegerField(blank=True, null=True)),
                (
                    "spectrum_quality_flag",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("spike_flag", models.SmallIntegerField(blank=True, null=True)),
                ("sensor_gain", models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "gosat_l1_quality_band",
            },
        ),
        migrations.CreateModel(
            name="ProfileLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layer_index", models.SmallIntegerField()),
                ("pressure_upper", models.FloatField(blank=True, null=True)),
                ("pressure_lower", models.FloatField(blank=True, null=True)),
                (
                    "pressure_weighting_function",
                    models.FloatField(blank=True, null=True),
                ),
                ("co2_profile", models.FloatField(blank=True, null=True)),
                ("co2_profile_apriori", models.FloatField(blank=True, null=True)),
                ("co2_profile_uncert", models.FloatField(blank=True, null=True)),
                ("ch4_profile", models.FloatField(blank=True, null=True)),
                ("ch4_profile_apriori", models.FloatField(blank=True, null=True)),
                ("ch4_profile_uncert", models.FloatField(blank=True, null=True)),
                ("co_profile", models.FloatField(blank=True, null=True)),
                ("co_profile_apriori", models.FloatField(blank=True, null=True)),
                ("co_profile_uncert", models.FloatField(blank=True, null=True)),
                ("h2o_profile", models.FloatField(blank=True, null=True)),
                ("h2o_profile_apriori", models.FloatField(blank=True, null=True)),
                ("h2o_profile_uncert", models.FloatField(blank=True, null=True)),
                ("aerosol_profile_type1", models.FloatField(blank=True, null=True)),
                (
                    "aerosol_profile_type1_apriori",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "aerosol_profile_type1_uncert",
                    models.FloatField(blank=True, null=True),
                ),
                ("aerosol_profile_type2", models.FloatField(blank=True, null=True)),
                (
                    "aerosol_profile_type2_apriori",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "aerosol_profile_type2_uncert",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "xco2_column_averaging_kernel",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "xch4_column_averaging_kernel",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "xco_column_averaging_kernel",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "xh2o_column_averaging_kernel",
                    models.FloatField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "gosat_profile_layer",
            },
        ),
        migrations.CreateModel(
            name="RetrievalSubbandParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subband_index", models.SmallIntegerField()),
                ("residual_reduced_chi2", models.FloatField(blank=True, null=True)),
                ("dispersion_adjustment", models.FloatField(blank=True, null=True)),
                (
                    "dispersion_adjustment_apriori",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "dispersion_adjustment_uncert",
                    models.FloatField(blank=True, null=True),
                ),
                ("ils_stretch_factor", models.FloatField(blank=True, null=True)),
                (
                    "ils_stretch_factor_apriori",
                    models.FloatField(blank=True, null=True),
                ),
                ("ils_stretch_factor_uncert", models.FloatField(blank=True, null=True)),
                ("zero_level_offset", models.FloatField(blank=True, null=True)),
                ("zero_level_offset_apriori", models.FloatField(blank=True, null=True)),
                ("zero_level_offset_uncert", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "gosat_retrieval_subband_parameter",
            },
        ),
        migrations.CreateModel(
            name="CloudInformation",
            fields=[
                (
                    "sounding",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cloud",
                        serialize=False,
                        to="carbon_tracker.sounding",
                    ),
                ),
                ("fts2_2um_flag_1", models.SmallIntegerField(blank=True, null=True)),
                ("fts2_2um_flag_2", models.SmallIntegerField(blank=True, null=True)),
                ("fts2_tir_flag_1", models.SmallIntegerField(blank=True, null=True)),
                ("fts2_tir_flag_2", models.SmallIntegerField(blank=True, null=True)),
                ("fts2_tir_flag_3", models.SmallIntegerField(blank=True, null=True)),
                ("ch4_ratio", models.FloatField(blank=True, null=True)),
                ("co2_ratio", models.FloatField(blank=True, null=True)),
                ("h2o_ratio", models.FloatField(blank=True, null=True)),
                ("surface_pressure_delta", models.FloatField(blank=True, null=True)),
                ("cai2_cldd", models.JSONField(blank=True, default=list)),
                ("cai2_coherent", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "gosat_cloud_information",
            },
        ),
        migrations.CreateModel(
            name="L1QualitySummary",
            fields=[
                (
                    "sounding",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="l1_quality_summary",
                        serialize=False,
                        to="carbon_tracker.sounding",
                    ),
                ),
                (
                    "sounding_quality_flag",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "scan_stability_flag",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("imc_stability_flag", models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "gosat_l1_quality_summary",
            },
        ),
        migrations.CreateModel(
            name="RetrievalResult",
            fields=[
                (
                    "sounding",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="retrieval",
                        serialize=False,
                        to="carbon_tracker.sounding",
                    ),
                ),
                ("xco2", models.FloatField(blank=True, db_index=True, null=True)),
                ("xco2_apriori", models.FloatField(blank=True, null=True)),
                ("xco2_uncert", models.FloatField(blank=True, null=True)),
                ("xco2_dfs", models.FloatField(blank=True, null=True)),
                (
                    "xco2_quality_flag",
                    models.SmallIntegerField(blank=True, db_index=True, null=True),
                ),
                ("xch4", models.FloatField(blank=True, db_index=True, null=True)),
                ("xch4_apriori", models.FloatField(blank=True, null=True)),
                ("xch4_uncert", models.FloatField(blank=True, null=True)),
                ("xch4_dfs", models.FloatField(blank=True, null=True)),
                (
                    "xch4_quality_flag",
                    models.SmallIntegerField(blank=True, db_index=True, null=True),
                ),
                ("xco", models.FloatField(blank=True, db_index=True, null=True)),
                ("xco_apriori", models.FloatField(blank=True, null=True)),
                ("xco_uncert", models.FloatField(blank=True, null=True)),
                ("xco_dfs", models.FloatField(blank=True, null=True)),
                (
                    "xco_quality_flag",
                    models.SmallIntegerField(blank=True, db_index=True, null=True),
                ),
                ("xh2o", models.FloatField(blank=True, null=True)),
                ("xh2o_apriori", models.FloatField(blank=True, null=True)),
                ("xh2o_uncert", models.FloatField(blank=True, null=True)),
                ("xh2o_dfs", models.FloatField(blank=True, null=True)),
                (
                    "xh2o_quality_flag",
                    models.SmallIntegerField(blank=True, db_index=True, null=True),
                ),
                ("dry_air_column", models.FloatField(blank=True, null=True)),
                ("dry_air_column_apriori", models.FloatField(blank=True, null=True)),
                ("surface_pressure", models.FloatField(blank=True, null=True)),
                ("surface_pressure_apriori", models.FloatField(blank=True, null=True)),
                ("surface_pressure_uncert", models.FloatField(blank=True, null=True)),
                ("wind_speed", models.FloatField(blank=True, null=True)),
                ("wind_speed_apriori", models.FloatField(blank=True, null=True)),
                ("wind_speed_uncert", models.FloatField(blank=True, null=True)),
                ("temperature_shift", models.FloatField(blank=True, null=True)),
                ("temperature_shift_apriori", models.FloatField(blank=True, null=True)),
                ("temperature_shift_uncert", models.FloatField(blank=True, null=True)),
                ("fluorescence_at_reference", models.FloatField(blank=True, null=True)),
                (
                    "fluorescence_at_reference_apriori",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "fluorescence_at_reference_uncert",
                    models.FloatField(blank=True, null=True),
                ),
                ("fluorescence_slope", models.FloatField(blank=True, null=True)),
                (
                    "fluorescence_slope_apriori",
                    models.FloatField(blank=True, null=True),
                ),
                ("fluorescence_slope_uncert", models.FloatField(blank=True, null=True)),
                ("iteration", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "gosat_retrieval_result",
            },
        ),
        migrations.CreateModel(
            name="AlbedoCoefficient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subband_index", models.SmallIntegerField()),
                ("coefficient_index", models.SmallIntegerField()),
                ("albedo", models.FloatField(blank=True, null=True)),
                ("albedo_apriori", models.FloatField(blank=True, null=True)),
                ("albedo_uncert", models.FloatField(blank=True, null=True)),
                (
                    "sounding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albedo_coefficients",
                        to="carbon_tracker.sounding",
                    ),
                ),
            ],
            options={
                "db_table": "gosat_albedo_coefficient",
            },
        ),
        migrations.AddField(
            model_name="sounding",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soundings",
                to="carbon_tracker.gosatproduct",
            ),
        ),
        migrations.AddIndex(
            model_name="gosatproduct",
            index=models.Index(
                fields=["file_id"], name="gosat_produ_file_id_9c33ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gosatproduct",
            index=models.Index(
                fields=["start_date", "end_date"], name="gosat_produ_start_d_cc9212_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gosatproduct",
            index=models.Index(
                fields=["satellite_name", "sensor_name"],
                name="gosat_produ_satelli_a2fe33_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="gosatproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("file_id", None), _negated=True),
                fields=("file_id",),
                name="uniq_gosat_product_file_id_not_null",
            ),
        ),
        migrations.AddField(
            model_name="h5datasetcatalog",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="h5_datasets",
                to="carbon_tracker.gosatproduct",
            ),
        ),
        migrations.AddField(
            model_name="l1qualityband",
            name="sounding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="l1_quality_bands",
                to="carbon_tracker.sounding",
            ),
        ),
        migrations.AddField(
            model_name="profilelayer",
            name="sounding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_layers",
                to="carbon_tracker.sounding",
            ),
        ),
        migrations.AddField(
            model_name="retrievalsubbandparameter",
            name="sounding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retrieval_subband_parameters",
                to="carbon_tracker.sounding",
            ),
        ),
        migrations.AddIndex(
            model_name="l1qualitysummary",
            index=models.Index(
                fields=["sounding_quality_flag"], name="gosat_l1_qu_soundin_8e8cb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="l1qualitysummary",
            index=models.Index(
                fields=["scan_stability_flag", "imc_stability_flag"],
                name="gosat_l1_qu_scan_st_1f6dde_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="retrievalresult",
            index=models.Index(
                fields=["xco2_quality_flag", "xch4_quality_flag"],
                name="gosat_retri_xco2_qu_0c2e34_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="retrievalresult",
            index=models.Index(
                fields=["xco_quality_flag", "xh2o_quality_flag"],
                name="gosat_retri_xco_qua_8b9810_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="retrievalresult",
            index=models.Index(fields=["xco2"], name="gosat_retri_xco2_366103_idx"),
        ),
        migrations.AddIndex(
            model_name="retrievalresult",
            index=models.Index(fields=["xch4"], name="gosat_retri_xch4_62cfba_idx"),
        ),
        migrations.AddIndex(
            model_name="retrievalresult",
            index=models.Index(fields=["xco"], name="gosat_retri_xco_24999c_idx"),
        ),
        migrations.AddIndex(
            model_name="albedocoefficient",
            index=models.Index(
                fields=["subband_index", "coefficient_index"],
                name="gosat_albed_subband_f08e89_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="albedocoefficient",
            constraint=models.UniqueConstraint(
                fields=("sounding", "subband_index", "coefficient_index"),
                name="uniq_albedo_coeff_per_sounding",
            ),
        ),
        migrations.AddIndex(
            model_name="sounding",
            index=models.Index(
                fields=["product"], name="gosat_sound_product_8a890d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sounding",
            index=models.Index(
                fields=["observation_time"], name="gosat_sound_observa_9cd079_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sounding",
            index=models.Index(
                fields=["latitude", "longitude"], name="gosat_sound_latitud_1ef4d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sounding",
            index=models.Index(
                fields=["sounding_unique_id"], name="gosat_sound_soundin_3d0013_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sounding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sounding_unique_id", None), _negated=True),
                fields=("product", "sounding_unique_id"),
                name="uniq_gosat_sounding_per_product",
            ),
        ),
        migrations.AddIndex(
            model_name="h5datasetcatalog",
            index=models.Index(
                fields=["h5_group"], name="gosat_h5_da_h5_grou_f24fce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="h5datasetcatalog",
            index=models.Index(
                fields=["dataset_name"], name="gosat_h5_da_dataset_4829ca_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="h5datasetcatalog",
            constraint=models.UniqueConstraint(
                fields=("product", "h5_path"),
                name="uniq_h5_dataset_catalog_per_product",
            ),
        ),
        migrations.AddIndex(
            model_name="l1qualityband",
            index=models.Index(
                fields=["band_index"], name="gosat_l1_qu_band_in_5bc41f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="l1qualityband",
            index=models.Index(
                fields=["spectrum_quality_flag"], name="gosat_l1_qu_spectru_c7140f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="l1qualityband",
            index=models.Index(
                fields=["missing_flag", "saturation_flag", "spike_flag"],
                name="gosat_l1_qu_missing_113f32_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="l1qualityband",
            constraint=models.UniqueConstraint(
                fields=("sounding", "band_index"),
                name="uniq_l1_quality_band_per_sounding",
            ),
        ),
        migrations.AddIndex(
            model_name="profilelayer",
            index=models.Index(
                fields=["layer_index"], name="gosat_profi_layer_i_42ec11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profilelayer",
            index=models.Index(
                fields=["pressure_upper", "pressure_lower"],
                name="gosat_profi_pressur_e316c6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilelayer",
            constraint=models.UniqueConstraint(
                fields=("sounding", "layer_index"),
                name="uniq_profile_layer_per_sounding",
            ),
        ),
        migrations.AddIndex(
            model_name="retrievalsubbandparameter",
            index=models.Index(
                fields=["subband_index"], name="gosat_retri_subband_8de4c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="retrievalsubbandparameter",
            index=models.Index(
                fields=["residual_reduced_chi2"], name="gosat_retri_residua_c72311_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="retrievalsubbandparameter",
            constraint=models.UniqueConstraint(
                fields=("sounding", "subband_index"),
                name="uniq_retrieval_subband_param_per_sounding",
            ),
        ),
    ]
