# Generated by Django 5.2.13 on 2026-07-07 02:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_type", models.CharField(max_length=32)),
                ("parameters", models.JSONField()),
                ("status", models.CharField(default="PENDING", max_length=16)),
                ("result_summary", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wind_analysis_jobs",
            },
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_time", models.DateTimeField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("metric_name", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "metric_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="wind_management.analysisjob",
                    ),
                ),
            ],
            options={
                "db_table": "wind_analysis_results",
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GRIDDED", "Gridded"),
                            ("STATION", "Station"),
                            ("SATELLITE", "Satellite"),
                            ("EVENT", "Event"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "source_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "spatial_extent",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("time_start", models.DateTimeField(blank=True, null=True)),
                ("time_end", models.DateTimeField(blank=True, null=True)),
                (
                    "temporal_resolution",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("RESTRICTED", "Restricted"),
                        ],
                        default="INTERNAL",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wind_datasets",
                "indexes": [
                    models.Index(
                        fields=["category"], name="wind_datase_categor_db5410_idx"
                    ),
                    models.Index(
                        fields=["access_level"], name="wind_datase_access__68cdc6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        help_text="Support multiple variables. e.g. [{'var': 'wind_speed', 'op': '>', 'val': 20}]"
                    ),
                ),
                (
                    "area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wind_management.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "wind_alert_rules",
            },
        ),
        migrations.CreateModel(
            name="DatasetAccessPolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view", models.BooleanField(default=True)),
                ("can_query", models.BooleanField(default=True)),
                ("can_download", models.BooleanField(default=False)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_policies",
                        to="wind_management.dataset",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataset_policies",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "db_table": "wind_dataset_access_policies",
            },
        ),
        migrations.CreateModel(
            name="DatasetVariable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variable_code", models.CharField(max_length=64)),
                ("variable_name", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="wind_management.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "wind_dataset_variables",
            },
        ),
        migrations.CreateModel(
            name="DownloadRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aoi_geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "station_ids",
                    models.JSONField(
                        blank=True, help_text="List of station IDs", null=True
                    ),
                ),
                ("time_start", models.DateTimeField()),
                ("time_end", models.DateTimeField()),
                ("status", models.CharField(default="PENDING", max_length=16)),
                (
                    "estimated_size_mb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wind_download_requests",
            },
        ),
        migrations.CreateModel(
            name="DownloadFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.TextField()),
                (
                    "file_size_mb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="wind_management.downloadrequest",
                    ),
                ),
            ],
            options={
                "db_table": "wind_download_files",
            },
        ),
        migrations.CreateModel(
            name="DownloadRequestItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variable_codes",
                    models.JSONField(help_text="List of variable codes"),
                ),
                ("export_format", models.CharField(max_length=16)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wind_management.dataset",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="wind_management.downloadrequest",
                    ),
                ),
            ],
            options={
                "db_table": "wind_download_request_items",
            },
        ),
        migrations.CreateModel(
            name="IngestionLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_file", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=16)),
                ("records_processed", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wind_management.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "wind_ingestion_logs",
            },
        ),
        migrations.CreateModel(
            name="MeteorologicalEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=255)),
                ("event_type", models.CharField(max_length=32)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "influence_area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "max_intensity",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "wind_meteorological_events",
                "indexes": [
                    models.Index(
                        fields=["event_type"], name="wind_meteor_event_t_c0bffc_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventTrack",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_time", models.DateTimeField()),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("intensity", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "central_pressure",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "moving_speed_kmh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "moving_direction",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="wind_management.meteorologicalevent",
                    ),
                ),
            ],
            options={
                "db_table": "wind_event_tracks",
            },
        ),
        migrations.CreateModel(
            name="RasterGranuleIndex",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_location", models.TextField()),
                ("granule_time", models.DateTimeField()),
                (
                    "elevation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "footprint",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                (
                    "variable_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raster_granules",
                        to="wind_management.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "wind_raster_granules_index",
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "elevation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "station_type",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stations",
                        to="wind_management.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "wind_stations",
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obs_time", models.DateTimeField()),
                (
                    "rain_06h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "rain_24h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "temp_2m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "temp_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "temp_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "pressure",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "wind_dir",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "wind_speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="wind_management.station",
                    ),
                ),
            ],
            options={
                "db_table": "wind_observations",
            },
        ),
        migrations.CreateModel(
            name="ExtremeEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extreme_type", models.CharField(max_length=32)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "peak_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "threshold_used",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wind_management.analysisjob",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wind_management.station",
                    ),
                ),
            ],
            options={
                "db_table": "wind_extreme_events",
            },
        ),
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=64)),
                ("metric_value", models.DecimalField(decimal_places=4, max_digits=15)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "wind_system_metrics",
                "indexes": [
                    models.Index(
                        fields=["metric_name", "-recorded_at"],
                        name="wind_system_metric__21917c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserQueryHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_type", models.CharField(max_length=32)),
                ("parameters", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wind_user_query_history",
            },
        ),
        migrations.CreateModel(
            name="AlertNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("triggered_at", models.DateTimeField()),
                (
                    "triggered_value",
                    models.JSONField(
                        blank=True,
                        help_text="Values that triggered the alert",
                        null=True,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="wind_management.alertrule",
                    ),
                ),
            ],
            options={
                "db_table": "wind_alert_notifications",
                "indexes": [
                    models.Index(
                        fields=["rule", "-triggered_at"],
                        name="wind_alert__rule_id_29b8bf_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="analysisjob",
            index=models.Index(
                fields=["user", "-created_at"], name="wind_analys_user_id_c6567a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisjob",
            index=models.Index(fields=["status"], name="wind_analys_status_df040b_idx"),
        ),
        migrations.AddIndex(
            model_name="analysisresult",
            index=models.Index(
                fields=["job", "result_time"], name="wind_analys_job_id_ffa682_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(fields=["user"], name="wind_alert__user_id_28edb6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="datasetaccesspolicy",
            unique_together={("dataset", "group")},
        ),
        migrations.AlterUniqueTogether(
            name="datasetvariable",
            unique_together={("dataset", "variable_code")},
        ),
        migrations.AddIndex(
            model_name="downloadrequest",
            index=models.Index(
                fields=["user", "-requested_at"], name="wind_downlo_user_id_f1fcf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="downloadrequest",
            index=models.Index(fields=["status"], name="wind_downlo_status_2d1e72_idx"),
        ),
        migrations.AddIndex(
            model_name="eventtrack",
            index=models.Index(
                fields=["event", "track_time"], name="wind_event__event_i_97ee21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rastergranuleindex",
            index=models.Index(
                fields=["dataset", "granule_time"],
                name="wind_raster_dataset_0aea5e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="station",
            unique_together={("dataset", "station_code")},
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["station", "obs_time"], name="wind_observ_station_56b774_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extremeevent",
            index=models.Index(
                fields=["station", "start_time"], name="wind_extrem_station_592d1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userqueryhistory",
            index=models.Index(
                fields=["user", "-created_at"], name="wind_user_q_user_id_980107_idx"
            ),
        ),
    ]
