# Generated by Django 5.2.10 on 2026-03-17 03:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("layers", "0046_remove_modeltranslation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MiningDetectionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID trả về từ AI service (POST /analyze → job_id)",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Tên mô tả cho phiên phân tích, VD: 'Quảng Ninh — Q1/2024'",
                        max_length=255,
                    ),
                ),
                (
                    "aoi_geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        help_text="Vùng phân tích (Area of Interest) dưới dạng Polygon WGS84",
                        srid=4326,
                    ),
                ),
                (
                    "date_from",
                    models.DateField(help_text="Ngày bắt đầu lấy ảnh Sentinel-2"),
                ),
                (
                    "date_to",
                    models.DateField(help_text="Ngày kết thúc lấy ảnh Sentinel-2"),
                ),
                (
                    "model_version",
                    models.CharField(
                        default="v2.1-sentinel",
                        help_text="Phiên bản model AI được sử dụng",
                        max_length=64,
                    ),
                ),
                (
                    "cloud_cover_pct",
                    models.FloatField(
                        default=20.0,
                        help_text="Ngưỡng mây tối đa cho phép (%) khi lấy ảnh WCS",
                    ),
                ),
                (
                    "extra_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tham số bổ sung gửi tới AI service (tile_size, threshold, ...)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "poll_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Số lần Celery đã poll /status từ AI service",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "shapefile_url",
                    models.URLField(
                        blank=True,
                        help_text="URL layer trên GeoNode (từ API result: shapefile_url)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User tạo job (giống ResourceBase.owner)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mining_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result_dataset",
                    models.OneToOneField(
                        blank=True,
                        help_text="GeoNode Dataset layer được upload từ AI service. Được quản lý hoàn toàn bởi ResourceBase — permissions, metadata, thumbnail do GeoNode xử lý.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mining_detection_job",
                        to="layers.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mining detection job",
                "verbose_name_plural": "Mining detection jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InferenceStatistics",
            fields=[
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="statistics",
                        serialize=False,
                        to="mining_detection.miningdetectionjob",
                    ),
                ),
                (
                    "total_area_ha",
                    models.FloatField(help_text="Tổng diện tích khai thác (hectare)"),
                ),
                (
                    "count",
                    models.PositiveIntegerField(help_text="Số lượng vùng phát hiện"),
                ),
                ("max_area_ha", models.FloatField(help_text="Diện tích vùng lớn nhất")),
                ("min_area_ha", models.FloatField(help_text="Diện tích vùng nhỏ nhất")),
                (
                    "avg_ndvi",
                    models.FloatField(
                        help_text="NDVI trung bình — âm = đất trống/khai thác"
                    ),
                ),
                (
                    "avg_ndwi",
                    models.FloatField(
                        help_text="NDWI trung bình — dương = có nước bề mặt"
                    ),
                ),
                (
                    "avg_bsi",
                    models.FloatField(
                        help_text="BSI trung bình — dương cao = đất trống/đá lộ thiên"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        default=dict,
                        help_text="Full JSON response từ GET /result/{job_id}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Inference statistics",
                "verbose_name_plural": "Inference statistics",
            },
        ),
        migrations.AddIndex(
            model_name="miningdetectionjob",
            index=models.Index(
                fields=["status", "created_at"], name="mining_dete_status_01ea54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="miningdetectionjob",
            index=models.Index(
                fields=["created_by", "status"], name="mining_dete_created_ff347f_idx"
            ),
        ),
    ]
