# Generated by Django 5.2.10 on 2026-03-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mining_detection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="date_from",
            field=models.DateField(
                blank=True, help_text="Ngày bắt đầu lấy ảnh Sentinel-2", null=True
            ),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="date_to",
            field=models.DateField(
                blank=True, help_text="Ngày kết thúc lấy ảnh Sentinel-2", null=True
            ),
        ),
    ]
