# Generated by Django 5.2.10 on 2026-03-17 14:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mining_detection", "0002_alter_miningdetectionjob_date_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="aoi_geom",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True,
                help_text="Vùng phân tích (Area of Interest) dưới dạng Polygon WGS84",
                null=True,
                srid=4326,
            ),
        ),
    ]
