# Generated by Django 5.2.12 on 2026-03-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mining_detection", "0003_alter_miningdetectionjob_aoi_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="shapefile_url",
            field=models.URLField(
                blank=True,
                help_text="URL layer trên GeoNode (từ API result: shapefile_url)",
                null=True,
            ),
        ),
    ]
