# Generated by Django 5.2.12 on 2026-03-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mining_detection", "0005_miningdetectionjob_result_execution_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="miningdetectionjob",
            name="message_progress",
            field=models.CharField(default=""),
        ),
        migrations.AddField(
            model_name="miningdetectionjob",
            name="progress_percentage",
            field=models.IntegerField(default=0),
        ),
    ]
