# Generated by Django 5.2.12 on 2026-03-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mining_detection", "0006_miningdetectionjob_message_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="message_progress",
            field=models.CharField(blank=True, default="", null=True),
        ),
    ]
