# Generated by Django 5.2.12 on 2026-03-24 04:48

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0046_remove_modeltranslation"),
        ("mining_detection", "0008_miningdetectionjob_base_dataset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoordinateSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "central_meridian",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Central Meridian",
                    ),
                ),
                (
                    "projection_zone",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Projection Zone",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Coordinate System",
                "verbose_name_plural": "Coordinate Systems",
                "db_table": "coordinate_system",
            },
        ),
        migrations.CreateModel(
            name="MineralType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Mineral Type",
                "verbose_name_plural": "Mineral Types",
                "db_table": "mineral_type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlanningZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Planning Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "approved_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Approved Date"
                    ),
                ),
                (
                    "document_reference",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Document Reference"
                    ),
                ),
            ],
            options={
                "verbose_name": "Planning Zone",
                "verbose_name_plural": "Planning Zones",
                "db_table": "planning_zone",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Province Name"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
                "db_table": "province",
            },
        ),
        migrations.AlterField(
            model_name="inferencestatistics",
            name="avg_bsi",
            field=models.FloatField(help_text="BSI trung binh"),
        ),
        migrations.AlterField(
            model_name="inferencestatistics",
            name="avg_ndvi",
            field=models.FloatField(help_text="NDVI trung binh"),
        ),
        migrations.AlterField(
            model_name="inferencestatistics",
            name="avg_ndwi",
            field=models.FloatField(help_text="NDWI trung binh"),
        ),
        migrations.AlterField(
            model_name="inferencestatistics",
            name="count",
            field=models.PositiveIntegerField(help_text="So luong vung phat hien"),
        ),
        migrations.AlterField(
            model_name="inferencestatistics",
            name="max_area_ha",
            field=models.FloatField(help_text="Dien tich vung lon nhat"),
        ),
        migrations.AlterField(
            model_name="inferencestatistics",
            name="min_area_ha",
            field=models.FloatField(help_text="Dien tich vung nho nhat"),
        ),
        migrations.AlterField(
            model_name="inferencestatistics",
            name="raw_response",
            field=models.JSONField(default=dict, help_text="Full JSON response"),
        ),
        migrations.AlterField(
            model_name="inferencestatistics",
            name="total_area_ha",
            field=models.FloatField(help_text="Tong dien tich khai thac (ha)"),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="aoi_geom",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True,
                help_text="Vung phan tich (AOI) duoi dang Polygon WGS84.",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="base_dataset",
            field=models.ForeignKey(
                blank=True,
                help_text="Dataset goc ma job nay dua tren.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mining_jobs_as_base",
                to="layers.dataset",
            ),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="cloud_cover_pct",
            field=models.FloatField(
                default=20.0,
                help_text="Nguong may toi da cho phep (%) khi lay anh WCS",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="created_by",
            field=models.ForeignKey(
                help_text="User tao job",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mining_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="date_from",
            field=models.DateField(
                blank=True, help_text="Ngay bat dau lay anh Sentinel-2", null=True
            ),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="date_to",
            field=models.DateField(
                blank=True, help_text="Ngay ket thuc lay anh Sentinel-2", null=True
            ),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="extra_params",
            field=models.JSONField(
                blank=True, default=dict, help_text="Tham so bo sung gui toi AI service"
            ),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="job_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="UUID tra ve tu AI service (POST /analyze -> job_id)",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="model_version",
            field=models.CharField(
                default="v2.1-sentinel",
                help_text="Phien ban model AI duoc su dung",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="poll_count",
            field=models.PositiveIntegerField(
                default=0, help_text="So lan Celery da poll /status tu AI service"
            ),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="progress_percentage",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="result_dataset",
            field=models.OneToOneField(
                blank=True,
                help_text="GeoNode Dataset duoc upload tu AI service.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mining_detection_job",
                to="layers.dataset",
            ),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="shapefile_url",
            field=models.URLField(
                blank=True, help_text="URL layer tren GeoNode", null=True
            ),
        ),
        migrations.AlterField(
            model_name="miningdetectionjob",
            name="title",
            field=models.CharField(
                help_text="Ten mo ta cho phien phan tich.", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="MiningSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.PositiveIntegerField(verbose_name="Serial Number"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Site Name")),
                (
                    "location_description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Location Description"
                    ),
                ),
                (
                    "area_ha",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Area (ha)",
                    ),
                ),
                (
                    "estimated_reserve_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Estimated Reserve (m3)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("licensed", "Licensed"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("exhausted", "Exhausted"),
                            ("restored", "Restored"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "coordinate_system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mining_sites",
                        to="mining_detection.coordinatesystem",
                        verbose_name="Coordinate System",
                    ),
                ),
                (
                    "mineral_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mining_sites",
                        to="mining_detection.mineraltype",
                        verbose_name="Mineral Type",
                    ),
                ),
                (
                    "planning_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mining_sites",
                        to="mining_detection.planningzone",
                        verbose_name="Planning Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mining Site",
                "verbose_name_plural": "Mining Sites",
                "db_table": "mining_site",
                "ordering": ["serial_number"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField(verbose_name="Recorded At")),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Period Type",
                    ),
                ),
                (
                    "actual_extraction_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Actual Extraction (m3)",
                    ),
                ),
                (
                    "remaining_reserve_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Remaining Reserve (m3)",
                    ),
                ),
                (
                    "inspector",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Inspector"
                    ),
                ),
                (
                    "violations_noted",
                    models.BooleanField(default=False, verbose_name="Violations Noted"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mining_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoring_records",
                        to="mining_detection.miningsite",
                        verbose_name="Mining Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitoring Record",
                "verbose_name_plural": "Monitoring Records",
                "db_table": "monitoring_record",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="District Name"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="districts",
                        to="mining_detection.province",
                        verbose_name="Province",
                    ),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "db_table": "district",
            },
        ),
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=10,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Penalty Amount (VND)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "monitoring_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="mining_detection.monitoringrecord",
                        verbose_name="Monitoring Record",
                    ),
                ),
            ],
            options={
                "verbose_name": "Violation",
                "verbose_name_plural": "Violations",
                "db_table": "violation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ward Name")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wards",
                        to="mining_detection.district",
                        verbose_name="District",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ward",
                "verbose_name_plural": "Wards",
                "db_table": "ward",
            },
        ),
        migrations.AddField(
            model_name="miningsite",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mining_sites",
                to="mining_detection.ward",
                verbose_name="Ward",
            ),
        ),
        migrations.CreateModel(
            name="BoundaryPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point_order",
                    models.PositiveSmallIntegerField(verbose_name="Point Order"),
                ),
                (
                    "x",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="X Coordinate (m)",
                    ),
                ),
                (
                    "y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Y Coordinate (m)",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=12,
                        null=True,
                        verbose_name="Latitude (WGS84)",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=12,
                        null=True,
                        verbose_name="Longitude (WGS84)",
                    ),
                ),
                (
                    "mining_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boundary_points",
                        to="mining_detection.miningsite",
                        verbose_name="Mining Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boundary Point",
                "verbose_name_plural": "Boundary Points",
                "db_table": "boundary_point",
                "ordering": ["mining_site", "point_order"],
                "unique_together": {("mining_site", "point_order")},
            },
        ),
    ]
