# Generated by Django 5.2.12 on 2026-03-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0046_remove_modeltranslation"),
        (
            "mining_detection",
            "0009_coordinatesystem_mineraltype_planningzone_province_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="miningsite",
            name="is_auto_monitoring",
            field=models.BooleanField(default=False, verbose_name="Tự động giám sát"),
        ),
        migrations.AddField(
            model_name="miningsite",
            name="monitoring_datasets",
            field=models.ManyToManyField(
                blank=True,
                related_name="monitored_mining_sites",
                to="layers.dataset",
                verbose_name="Monitoring Datasets",
            ),
        ),
    ]
