# Generated by Django 5.2.12 on 2026-04-01 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mining_detection", "0012_miningdetectionjob_tif_result_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="miningsite",
            name="auto_monitoring_inference_params",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="Auto Monitoring Inference Params",
            ),
        ),
        migrations.AddField(
            model_name="miningsite",
            name="auto_monitoring_interval_days",
            field=models.PositiveIntegerField(
                default=7,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
                verbose_name="Auto Monitoring Interval (days)",
            ),
        ),
        migrations.AddField(
            model_name="miningsite",
            name="auto_monitoring_last_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Auto Monitoring Last Requested At"
            ),
        ),
        migrations.AddField(
            model_name="miningsite",
            name="auto_monitoring_model_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Auto Monitoring Model ID",
            ),
        ),
    ]
