# Generated by Django 5.2.12 on 2026-05-05 13:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("xco2_ppm", models.FloatField()),
                ("xco2_uncertainty_ppm", models.FloatField(blank=True, null=True)),
                ("xco2_quality_flag", models.IntegerField(default=0)),
                ("surface_pressure_hpa", models.FloatField(blank=True, null=True)),
                ("solar_zenith_angle_deg", models.FloatField(blank=True, null=True)),
                ("view_zenith_angle_deg", models.FloatField(blank=True, null=True)),
                ("cloud_flag", models.IntegerField(blank=True, null=True)),
                ("land_fraction", models.FloatField(blank=True, null=True)),
                (
                    "data_source",
                    models.CharField(
                        choices=[("OCO2", "OCO-2"), ("GOSAT2", "GOSAT-2")],
                        max_length=10,
                    ),
                ),
                ("measurement_time", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeasurementSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_format",
                    models.CharField(
                        choices=[("NETCDF4", "netCDF4"), ("HDF5", "HDF5")],
                        max_length=10,
                    ),
                ),
                (
                    "file_size_mb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("measurement_date", models.DateField(blank=True, null=True)),
                ("total_soundings", models.IntegerField(blank=True, null=True)),
                ("quality_checked", models.BooleanField(default=False)),
                (
                    "processing_level",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "algorithm_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA-256 hash to prevent duplicates",
                        max_length=64,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonitoringLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=255)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("CITY", "City"),
                            ("REGION", "Region"),
                            ("INDUSTRIAL", "Industrial Area"),
                            ("RESEARCH", "Research Station"),
                        ],
                        max_length=20,
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("radius_km", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Satellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("satellite_name", models.CharField(max_length=50)),
                ("launch_date", models.DateField(blank=True, null=True)),
                ("operator", models.CharField(max_length=100)),
                (
                    "orbital_altitude_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "orbital_period_minutes",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "orbital_inclination_deg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("INSERT", "Insert"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("QUERY", "Query"),
                        ],
                        max_length=10,
                    ),
                ),
                ("table_name", models.CharField(max_length=100)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="co2_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spatial_distance_km", models.FloatField()),
                ("xco2_difference_ppm", models.FloatField()),
                (
                    "comparison_type",
                    models.CharField(
                        choices=[
                            ("SPATIAL", "Spatial"),
                            ("TEMPORAL", "Temporal"),
                            ("RANDOM", "Random"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "gosat2_measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gosat2_comparisons",
                        to="co2_management.measurement",
                    ),
                ),
                (
                    "oco2_measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oco2_comparisons",
                        to="co2_management.measurement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeasurementMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_xco2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "max_xco2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "mean_xco2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("coverage_stats", models.JSONField(blank=True, null=True)),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="co2_management.measurementsource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="measurement",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="co2_management.measurementsource",
            ),
        ),
        migrations.CreateModel(
            name="AnalysisJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("COMPARISON", "Comparison"),
                            ("TREND", "Trend Analysis"),
                            ("ANOMALY", "Anomaly Detection"),
                            ("EXPORT", "Data Export"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                (
                    "result_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co2_analysis_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="analysis_jobs",
                        to="co2_management.measurementsource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QualityAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quality_score", models.IntegerField(help_text="0-100")),
                ("is_valid", models.BooleanField(default=True)),
                ("validation_flags", models.JSONField(default=dict)),
                ("error_messages", models.TextField(blank=True, null=True)),
                (
                    "measurement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality",
                        to="co2_management.measurement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="measurementsource",
            name="satellite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="co2_management.satellite",
            ),
        ),
        migrations.CreateModel(
            name="SatelliteInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument_name", models.CharField(max_length=50)),
                ("spectral_bands", models.IntegerField(blank=True, null=True)),
                (
                    "spectral_range_min_nm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "spectral_range_max_nm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "spatial_resolution_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "satellite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruments",
                        to="co2_management.satellite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemporalSeries",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("measurement_date", models.DateField()),
                ("xco2_ppm", models.FloatField()),
                (
                    "data_source",
                    models.CharField(
                        choices=[("OCO2", "OCO-2"), ("GOSAT2", "GOSAT-2")],
                        max_length=10,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="co2_management.monitoringlocation",
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="co2_management.measurement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerticalProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("level_index", models.IntegerField()),
                ("pressure_hpa", models.FloatField(blank=True, null=True)),
                ("co2_concentration_ppm", models.FloatField(blank=True, null=True)),
                ("co2_uncertainty_ppm", models.FloatField(blank=True, null=True)),
                ("temperature_k", models.FloatField(blank=True, null=True)),
                ("averaging_kernel", models.FloatField(blank=True, null=True)),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="co2_management.measurement",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["source", "measurement_time"],
                name="co2_managem_source__b2686a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["data_source", "xco2_quality_flag", "xco2_ppm"],
                name="co2_managem_data_so_ac3b41_idx",
            ),
        ),
    ]
