# Generated by Django 5.2.13 on 2026-05-11 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("co2_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacomparison",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparisons",
                to="co2_management.analysisjob",
            ),
        ),
    ]
