# Generated by Django 5.2.13 on 2026-07-24 02:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("co2_management", "0003_station_stationmeasurement"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
